### ISSUE TITLE
try to use relative path here

### ISSUE THREAD

**Issue by cgrad01** [marmar32/prj-rev-bwfs-dasmoto#1]
currently you are using the full path to the css file on your machine, which makes this link not work in any other context. To avoid this problem use the relative path, which looks like this:

`<link href="Dasmato CSS/Dasmatos.css" type="text/css" rel="stylesheet">`

By going all the way back to you user directory, and your user folder, this file becomes not found on any other machine. I fixed this before grading your work to see the css that you were seeing locally.

https://github.com/marmar32/prj-rev-bwfs-dasmoto/blob/master/Damotos%20Art/Dasmatos.html#L4

**Comment by marmar32** [comment]
Ah i had copied full path my apologies! Thank you so much for your review, sorry it took so long to get back we wre in the middle of moving and my mom threw her back! 
Marwa
