### ISSUE TITLE
a lot of repeated code

### ISSUE THREAD

**Issue by cgrad01** [marmar32/prj-rev-bwfs-dasmoto#4]
would like to see you try isolate the common traits and assign those to the h2, so we don't need to repeat those for each ID. The only that changes for the IDs is the color.

https://github.com/marmar32/prj-rev-bwfs-dasmoto/blob/master/Damotos%20Art/Dasmato%20CSS/Dasmatos.css#L14-L26

**Comment by marmar32** [comment]
got it!
