### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by cgrad01** [marmar32/prj-rev-bwfs-dasmoto#5]
Grade: Meets Expectations

Once the css link was adjusted, I thought this project looked good in the browser, and showed a good understanding of the html elements and had a nice consistent structure. I pointed to a couple areas where things could be tightened up. I would suggest taking a second look at the css file, and see if you can accomplish the same styles in less lines of code. You definitely got things to the point where they work, but now you need to refine your methods there. [Here is a brief article if you have more questions about how to work with different kind of paths.](http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/)

As a further challenge I would suggest adding an About Dasmoto page, and linking that to your homepage you have already made. You may need to review past lessons to do this but I think you are up to the challenge!

**Comment by marmar32** [comment]
Thank you so much!
